### PR TITLE
chore: integrate REUSE tool

### LINKED ISSUE #155: [rl-license_file-3] Violation against OSS Rules of Play
A violation against the OSS Rules of Play has been detected.

Rule ID: rl-license_file-3
Explanation: Does the license have disallowed content? **Yes**

Find more information at: https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html

### LINKED ISSUE #156: [rl-reuse_tool-2] Violation against OSS Rules of Play
A violation against the OSS Rules of Play has been detected.

Rule ID: rl-reuse_tool-2
Explanation: Does it have LICENSES directory with licenses? **No**

Find more information at: https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html

### LINKED ISSUE #157: [rl-reuse_tool-1] Violation against OSS Rules of Play
A violation against the OSS Rules of Play has been detected.

Rule ID: rl-reuse_tool-1
Explanation: Does README mention REUSE? **No**

Find more information at: https://sap.github.io/fosstars-rating-core/oss_rules_of_play_rating.html

### PR DESCRIPTION
**Pull request by SebastianWolf-SAP**
In line with SAP OSPO requirements, this PR integrates the REUSE tool, cleans up the LICENSE.txt file and removes the obsolete NOTICE.txt file

**Notes:** 
- Please [register the repository with the REUSE Tool](https://api.reuse.software/register) to complete the integration (see #158 and #159)
- This PR is in draft state as the references to the two dependencies that were mentioned in the LICENSE.txt weren't taken over to the dep5 file. I couldn't find these files that were there... @hborisov @parvandobrev @karaimin In case they are somewhere (probably under another name), please reference them in the .reuse/dep5 file under their proper name and update the PR. Edits by maintainers is switched on. Thanks!

Fixes #155
Fixes #156
Fixes #157

### CODE REVIEW

**Review by hborisov — APPROVED** [review]

**Comment by SebastianWolf-SAP** [comment]
@hborisov Thanks for the fast approval! However, before I make it a real PR and merge it, any comment from your end on the 3rd-party components? I'd need a confirmation that there is no 3rd party code directly integrated in the project. Otherwise the proposed changes wouldn't be correct. Thanks in advance!

**Comment by hborisov** [comment]
Hello Sebastian,
we've started the project using a few classes from the OSIAM project (https://github.com/osiam/osiam).

**Comment by SebastianWolf-SAP** [comment]
OK, could you please specify these files in the dep5 file (see https://reuse.software/tutorial/) so that their copyright is outlined correctly? Thanks!

In addition, what happened with the things from ChangeDistiller and Dependency Finder?

**Comment by karaimin** [comment]
Hi @SebastianWolf-SAP,
The LICENSE of the OSIAM projects class files that we reuse is placed in the content on each of them. See [here](https://github.com/SAP/scimono/blob/master/scimono-server/src/main/java/com/sap/scimono/entity/Address.java)

Do we need to specify them in the dep5 file as well?

**Comment by karaimin** [comment]
Hi @SebastianWolf-SAP,
I will merge this PR and open a new one if other changes are needed (according to my comment above)

**Comment by SebastianWolf-SAP** [comment]
@karaimin Yes, the changes are needed - as said, otherwise the REUSE integration is not correct. Please mention the MIT-licensed files in the .reuse/dep5 file explicitly, so that they overrule the wildcard. If you need help, please let me know - be sure to have the list of differently licensed files ready, so I can assist.

**Pull request merged**
